name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pruebas unitarias con Ant
      run: |
        sudo apt install -y default-jdk ant
        echo $SHELL
        echo $USER
        pwd
        ant test
